### ISSUE TITLE
Control Device - TRV

### ISSUE THREAD

**Issue by petersturrock** [eWeLinkCUBE/node-red-contrib-ewelink-cube#1]
First of all, many thanks for this repo. It's let me create some heating control logic that I can't achieve in iHost.

Is it possible to add control device logic to allow control of the Sonoff TRVs? This should allow control of the TRVs using external temperature sensors.

**Comment by SuiKaSan** [comment]
Sorry about the delay.
By saying allow control of the TRVs using external temperature sensors.
I can list two scenario below:
1. Register a virtual device as temperature sensor in iHost and use it in scene to control TRVs.
2. Set up the temperature sensor in node-red and upload temperature info to control TRVs.

First one is feasible and supported in iHost.
But the second one is not. Because TRVs is not supported in node-red yet.

**Comment by petersturrock** [comment]
Thanks for the follow up.

Ideally I'd like to do (2) so I can have all the logic in Node Red and set the temperatures on TRVs based on various sensors I have installed in Node Red.

(1) might help with some logic that I need. I have successfully registered a virtual temp sensor with 'Register Device'. But I'm currently having difficulty setting the temperture using the 'Put Device State'. I'm getting a 'not properly configured' error when I select the virtual temp sensor.

Should the put node allow me to change the value of the virtual temp sensor?

**Comment by SuiKaSan** [comment]
Can you send me a screenshot of your virtual device node configuration so I can pinpoint the problem?

**Comment by petersturrock** [comment]
<img width="446" alt="image" src="https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/79808045/8ddeaa52-d7f9-4467-b9ef-2f622599ec9f">

This is my latest attempt. The device is created but I can't create a valid 'Put Device State' node to set and change the values. I first tried to create a temperature only sensor but wasn't able to use 'Device Initial State' to initialise the values.

**Comment by SuiKaSan** [comment]
Please post your put-device-state node configuration as well.

**Comment by SuiKaSan** [comment]
I tried to register a virtual temperature sensor and reproduce the problem.
Here are some results.

1. Use 'Device Innitial State' to initialise the temperature:
![lQLPJwSivSyvhtfNA8LNBwCwUQhMIYrDhzwFoUbuecPQAA_1792_962](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/44567811/d56f1de9-5546-4a10-b1de-a28ce5461ac9)
![lQLPKG4gu-PeLhfM-c0CK7BkwD7RR7dAOAWhRxEFBU0A_555_249](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/44567811/0046d843-5039-47c0-8714-51c90dd6651f)

2. Use 'Put Device State' node to change temperature:
![f85ca84781de5a73de2795ffe11b8f97](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/44567811/8a199e75-a742-48e3-9708-d39383512499)
![8f775740ee766f6f73113833e727e0e2](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/44567811/dec84229-1d7f-481a-b53d-3078de23adb5)
![e45429b75b868b9471c575f6ac0352d9](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/44567811/e6d4370a-57e9-4987-b38a-c31ee2d28e5c)

Both of them working pretty well.
Please double check your configuration with mine.

**Comment by petersturrock** [comment]
I've recreated the above and added the JSON for the initial state and inject. It works and updates the temperature but I always get a red triangle in the put-device-state and an error during the deploy 

![image](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/79808045/c384ed31-a6d3-43a3-a261-93b36b308de3)

![image](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/79808045/5ae9995b-3171-4d8b-af15-e6d961d27ab8)

![image](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/79808045/ae55d028-c48c-4cfa-bb3c-81388e3be980)

**Comment by SuiKaSan** [comment]
Can you take a full screenshot of your put-device-state node?
Might be your configuration's problem.

**Comment by SuiKaSan** [comment]
It's a known bug but won't affect any of your node's behavior besides warning.
We'll fix it in next version of node-red-contrib-ewelink-cube.

**Comment by petersturrock** [comment]
Thanks for the investigation on this. Do you know if the control device node will be upgraded to allow TRV control ?

**Comment by SuiKaSan** [comment]
TRV will be supported in the end of next month.
