### ISSUE TITLE
Contact sensor event-state node states

### ISSUE THREAD

**Issue by rdaraujo** [eWeLinkCUBE/node-red-contrib-ewelink-cube#3]
I have some contact sensors that used to work great.
But, for some reason after **eWeLink CUBE 2.0.0** update, all them stopped updating states on **Node RED**, although they work normally on iHost.

![image](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/6662129/17752c19-28ea-4557-96d4-e59dc3b5e2b8)

I can't remember what options it had before as _State_, but now it shows only _Battery_ state and I suspect the lack of a "contact" state (opened/closed) causes the component to be useless when used with a contact sensor.

![image](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/6662129/d4eeda5f-317c-4ca5-af18-e28294481650)

As a matter of fact, a temperature sensor I have shows all possible states as expected:

![image](https://github.com/eWeLinkCUBE/node-red-contrib-ewelink-cube/assets/6662129/77ffdf76-e159-4ee4-8333-3cdf89394312)

node-red-contrib-ewelink-cube version: 1.2.2
eWeLink CUBE version: 2.0.0

**Comment by rdaraujo** [comment]
Same problem occurs in the **homebridge-plugin-ewelink-cube**.
No state updates for any contact sensor anymore (Aqara Door/Window ZigBee Sensor - **MCCGQ11LM**).

Log shows:
`[6/25/2024, 4:54:54 PM] [homebridge-plugin-ewelink-cube] This plugin generated a warning from the characteristic 'Contact Sensor State': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.`

**Comment by SuiKaSan** [comment]
Please upgrade your node-red-contrib-ewelink-cube to version 1.2.4.
Then you should be able to receive the state in event-state node with "All" option selected.

It's a temporary workaround.
We'll release a new version to completely fix the problem.

**Comment by SuiKaSan** [comment]
We're also trying to fix the problem in homebridge-plugin-ewelink-cube.
We'll let you know if anything new release.
